# @package _group_
common:
  fp16: True
  log_format: json
  log_interval: 50
  tensorboard_logdir: /mnt/lustre/wangzhijun2/mix-bert/mix-phoneme-bert/2b/tensorboard
  
checkpoint:
  no_epoch_checkpoints: true

task:
  _name: masked_lm
  data: /mnt/lustre/wangzhijun2/mix-bert/data/5kw-new/bpe/bin
  sample_break_mode: complete
  tokens_per_sample: 510
  mask_whole_words: True
  sentencepiece_model: /mnt/lustre/wangzhijun2/mixbert/2b/spm.model

criterion: masked_lm

dataset:
  batch_size: 128
  ignore_unused_valid_subsets: true
  skip_invalid_size_inputs_valid_test: True
  num_workers: 0

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 10000

optimization:
  clip_norm: 0
  lr: [0.0007]
  max_update: 125000
  update_freq: [8]

model:
  _name: roberta
  max_positions: 512
  dropout: 0.1
  attention_dropout: 0.1
  encoder_embed_dim: 256
  encoder_ffn_embed_dim: 1024
  encoder_attention_heads: 8
  encoder_layers: 6
